### ISSUE TITLE
State if the handling of back-pressure is part of the scope of this library

### ISSUE THREAD

**Issue by sledorze** [funfix/funfix.js#51]

**Comment by alexandru** [comment]
@sledorze I'm not sure what you mean. 

When talking of "*back-pressure*", that's usually in the context of streaming abstractions / data types and for the time being we have no such data types exposed by Funfix.

The plan is to eventually port [Monix](https://monix.io) ([github](https://github.com/monix/) | [twitter](https://twitter.com/monix)), however that might happen in a different project that will depend on Funfix, because I got [npmjs.com/package/monix](https://www.npmjs.com/package/monix) and it would be a shame to not use it 😃

**Comment by sledorze** [comment]
@alexandru Indeed, that's exactly what I'm looking for.. 
I've not at all looked into it but it just comes to my mind that maybe the scalajs API version of Monix may be usable in a pure js (Typescript / Flow) ? (I'm saying that without knowing much how Monix or ScalaJs work under the hood)
Otherwise, do you know of any alternate solution for the time being?

**Comment by alexandru** [comment]
@sledorze the Scala.js version of Monix is optimized for Scala and it isn't my intention to expose that to JavaScript, just like I haven't done any optimizations for using Monix from Java either. 

I'm also not sure what changes that would require either. If you think it can be done easily, then PRs are welcome.

But as I said, I do intend to start porting it to TypeScript / Flow / JavaScript. It might take some time though, I don't have an ETA.

**Comment by sledorze** [comment]
@alexandru thanks for the feedback.
My need is pretty urgent I'll try to put something in shape just for my needs, lurking on your activity..

**Comment by alexandru** [comment]
Cool, I'm going to close this for now, we'll be in touch.
