### ISSUE TITLE
Missing dependencies to build

### ISSUE THREAD

**Issue by graph1zzlle** [funfix/funfix.js#56]
Hi :)

I just cloned the project and wanted to try to build the project, so I did:
```
npm install && learn run build
```

and it couldn't build out of the box. I needed to add 2 dependencies that are not in `package.json`, which are `lodash` & `shelljs`.

Cheers,
Clément.

**Comment by alexandru** [comment]
I'm personally using `yarn` instead of `npm` for local development, they should be equivalent, but maybe in your invocation there's some step that you're missing.

So I do ...

```
yarn && yarn build
```

That build task should do `lerna run build` on its own.

If the problem persists, can you please copy/paste the error message?

**Comment by graph1zzlle** [comment]
No problem using `yarn && yarn build` :) Thanks !
