### ISSUE TITLE
IO.flatMap never ends when imported from different packages

### ISSUE THREAD

**Issue by lostintime** [funfix/funfix.js#83]
Currently using `funfix` in [a package](https://www.npmjs.com/package/typematcher-funfix) which includes only `funfix-effect` package, but when using that package as a dependency - `IO.flatMap` never ends.

__Dependencies__
```typescript
{
  "dependencies": {
    "funfix": "^6.2.2",
    "funfix-effect": "^6.2.2",
    "funfix-exec": "^6.2.2"
  },
  "devDependencies": {
    "typescript": "^2.6.2"
  }
}
```

__Working example__
```typescript
import { IO } from "funfix-effect"
import { Future } from "funfix-exec"

const one = IO.once(() => 10)
const two = IO.deferFuture(() => Future.pure(20))

one
  .flatMap(_ => two)
  .runOnComplete(() => {
    console.log("done")
  })
```

__This also works__
```typescript
import { IO, Future } from "funfix"

const one = IO.once(() => 10)
const two = IO.deferFuture(() => Future.pure(20))

one
  .flatMap(_ => two)
  .runOnComplete(() => {
    console.log("done")
  })
```

__Not Working (never ends)__
```typescript
import { IO } from "funfix-effect"
import { Future } from "funfix" // <<<< difference

const one = IO.once(() => 10)
const two = IO.deferFuture(() => Future.pure(20))

one
  .flatMap(_ => two)
  .runOnComplete(() => {
    console.log("done")
  })
```

__Plain JS not working also__
```javascript
const { IO } = require("funfix-effect")
const { Future } = require("funfix")

const one = IO.once(() => 10)
const two = IO.deferFuture(() => Future.pure(20))

one
  .flatMap(_ => two)
  .runOnComplete(() => {
    console.log("done")
  })
```

**Comment by alexandru** [comment]
@lostintime I'll have to check the code, but right now my assumption is that the problem is in how the main `funfix` package gets assembled.

Basically everything gets backed into `funfix`, it's not just doing a plain re-export. So the `Future` from `funfix` is actually a different constructor from the `Future` in `funfix-exec`.

I did this in order for the browser import to work without issues, due to the project being modular, however I'm now thinking that this is a mistake.

In the next `7.0.0` release candidate we might as well get rid of this problematic bundling and just let people import multiple `<script>` tags.

Or maybe we could do a single file just for the browser, e.g. `funfix/dist/browser` or something. Still thinking about it.

But I have to understand the problem, because even if we have different JS constructors in there, it should have worked IMO.

**Comment by alexandru** [comment]
Well, actually, having encountered such problems before, I don't want to investigate b/c it's a time waste.

I reconfigured `funfix` to not bundle its sub-projects, see issue #109. This means that exports now are accomplished via the normal JS export mechanisms (whether it's ES2015 modules or AMD).
