### ISSUE TITLE
Problem with funfix in Angular 5 project with IE11 browser

### ISSUE THREAD

**Issue by tosun-si** [funfix/funfix.js#96]
Firstly, thanks for this API, i really like it.

I have a problem. I Use funfix "^6.2.2" in an Angular 5 project (with npm and webpack) and i have an anomaly only in the IE11 browser.

This API works fine on firefox and chrome.

This API is it compatible with IE11 ?

I have the following error in IE 11 : 

/***/ "../../../../funfix-core/dist/std.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* harmony export (immutable) */ __webpack_exports__[\"g\"] = isValueObject;\n/* harmony 

![image](https://user-images.githubusercontent.com/12008156/36025679-2b39b776-0d94-11e8-8af9-07cec2fdec48.png)

![image](https://user-images.githubusercontent.com/12008156/36025692-3a7f97be-0d94-11e8-9812-ef958ae3ae45.png)

Can you help me please ?

**Comment by alexandru** [comment]
Hi @tosun-si, not sure what to tell you, but Funfix does not use Webpack in its bundle, so it's probably your setup.

One thing you could try, if you're using Webpack, is to use the ES5 bundle ... this means importing `dist/es5` instead of your import. This bundle was made for Webpack compatibility btw.

Also I have the feeling that you're importing `funfix-core/dist/std`, but you shouldn't depend directly on files like that. `funfix-core` is small enough and if you're using Webpack you probably want to use its minifier anyway.

So try this:

```
import { ... } from "funfix-core/dist/es5"
```

And let me know.

**Comment by alexandru** [comment]
PS: it might work fine in Firefox and Chrome for the sole reason that these are modern browsers supporting ES2015 features. Which is why you need the `es5` bundle ;-)

**Comment by tosun-si** [comment]
Hi @alexandru.
Thank you very much for your help.

I tried with import { ... } from "funfix-core/dist/es5" but i have the same problem.

**Comment by tosun-si** [comment]
Had you tried to use funfix in an Angular 5 project with typescript (and webpack) ?

**Comment by tosun-si** [comment]
Hi @alexandru.

Finally, it woks on on IE11 with :

import * as core from "funfix-core/dist/es5"

Thanks again for your help :)

**Comment by alexandru** [comment]
@tosun-si I'm very glad it worked.

Will close this for now.

Cheers,
